import distributed
import json

def parse_args(base_parser, args, namespace):
    parser = base_parser
    # General training params
    parser.add_argument("--experiment_name", default=None, type=str)
    parser.add_argument("--seed", default=0, type=int)
    parser.add_argument("--data_seed", default=1337, type=int)
    parser.add_argument("--eval_interval", default=200, type=int)
    parser.add_argument("--full_eval_at", nargs="+", type=int)
    parser.add_argument("--eval_batches", default=32, type=int)
    parser.add_argument("--device", default="cuda:0", type=str)
    parser.add_argument(
        "--distributed_backend",
        default=None,
        type=str,
        required=False,
        choices=distributed.registered_backends(),
    )
    parser.add_argument("--log_interval", default=50, type=int)

    # Checkpointing
    parser.add_argument("--results_base_folder", default="./exps", type=str)
    parser.add_argument("--permanent_ckpt_interval", default=0, type=int)
    parser.add_argument("--latest_ckpt_interval", default=0, type=int)
    parser.add_argument("--resume_from", default=None, type=str)
    parser.add_argument("--resume_from_swa", default=None, type=str)
    parser.add_argument("--auto_resume", default=False)
    parser.add_argument("--limit_iters_to", default=-1, type=int)

    # logging params (WandB)
    parser.add_argument("--wandb", action="store_true")  # whether to use wandb or not
    parser.add_argument("--wandb_entity", default="ist", type=str)
    parser.add_argument("--wandb_project", default="my-project", type=str)
    parser.add_argument("--wandb_group", required=True, type=str)
    parser.add_argument("--wandb_job_type", required=True, type=str)
    parser.add_argument("--wandb_run_prefix", default="none", type=str)  # is added before the autogenerated experiment name
    parser.add_argument("--eval_seq_prefix", default="none", type=str)  # prefix used to generate sequences
    parser.add_argument("--log_dynamics", action="store_true")
    parser.add_argument("--dynamics_logger_cfg", default="./src/logger/rotational_logger.yaml", type=str)

    # Schedule
    parser.add_argument("--scheduler", default="cos", choices=["linear", "cos", "wsd", "none", "cos_inf"])
    parser.add_argument("--cos_inf_steps", default=0, type=int)
    # parser.add_argument("--cos_final_lr", default=1e-6, type=float)
    parser.add_argument("--iterations", default=15000, type=int)
    parser.add_argument("--warmup_steps", default=300, type=int)
    parser.add_argument("--lr", default=1e-3, type=float)
    # wsd
    parser.add_argument("--wsd_final_lr_scale", default=0.0, type=float)
    parser.add_argument("--wsd_fract_decay", default=0.1, type=float)
    # parser.add_argument("--wsd_exponential_decay", action="store_true")
    parser.add_argument("--decay_type", default="linear", choices=["linear", "cosine", "exp", "miror_cosine", "square", "sqrt"])
    # Optimization
    parser.add_argument("--opt", default="adamw", choices=[
        "adamw", "sgd", "SFAdamW",
        "adopt", "mars", "shampoo", "scalable-shampoo", "muon", "scion",
        "dion", "dion-s", "dion-r",
        "ns-dct-dion",
        "dist-shmp", "dash-lw", "dash-gpu",
        "graft-muon",
        "subtrack", "dctadamw",
        "custom-ema-adamw", "frugal-micro-adam", "trion", "trionosd", "trionwadam", "scioned-soap"
    ])
    # parser.add_argument("--use_sparse_grad", default=0, type=int, help="whether to sparsify gradients")

    parser.add_argument("--batch_size", default=50, type=int)
    parser.add_argument("--acc_steps", default=4, type=int)
    parser.add_argument("--weight_decay", default=1e-1, type=float)
    parser.add_argument("--grad_clip", default=1.0, type=float)  # default value is 1.0 in NanoGPT

    # Weight Averaging
    parser.add_argument("--weight_average", action="store_true")
    parser.add_argument("--wa_interval",
        default=5,
        type=int,
        help="How often to take the average (every k steps). Must divide wa-horizon.",
    )
    parser.add_argument(
        "--wa_horizon",
        default=500,
        type=int,
        help="How frequently we save uniform model averages. Should divide "
        + "latest-ckpt-interval, otherwise some points may not be saved "
        + "correctly.",
    )
    parser.add_argument(
        "--wa_dtype",
        default="float32",
        type=str,
        choices=["float32", "float64"],
    )

    parser.add_argument("--wa_use_temp_dir", action="store_true")
    parser.add_argument("--wa_sweep_horizon", action="store_true")
    parser.add_argument("--max_num_wa_sweeps", default=5, type=int)

    parser.add_argument("--exponential_moving_average", action="store_true")
    parser.add_argument("--ema_interval", default=10, type=int, help="How often to take the EMA average (every k steps).")
    parser.add_argument("--ema_decay", default=0.95, type=float, help="EMA decay parameter (between 0.9 and 1).", )
    parser.add_argument("--ema_after_warmup", action="store_true", help="Start EMA after warmup steps.", )

    # Dataset params
    parser.add_argument("--datasets_dir", type=str, default="./datasets/")
    parser.add_argument(
        "--dataset",
        default="slimpajama",
        choices=[
            "wikitext",
            "shakespeare-char",
            "arxiv",
            "arxiv2000",
            "arxiv+wiki",
            "openwebtext2",
            "redpajama",
            "slimpajama",
            "slimpajama_chunk1",
            "redpajamav2",
            "c4",
            "fineweb",
        ],
    )
    parser.add_argument("--tokenizer", default="gpt2", type=str, choices=["gpt2", "mistral"])
    parser.add_argument("--vocab_size", default=50304, type=int)
    parser.add_argument("--data_in_ram", action="store_true")  # force the data to RAM, mostly useless except for openwebtext2

    # Model params
    parser.add_argument("--model", default="llama", choices=["base", "llama",])
    parser.add_argument("--parallel_block", action="store_true")
    parser.add_argument("--use_pretrained", default="none", type=str)  # 'none', 'gpt-2' or a path to the pretraind model
    parser.add_argument("--from_dense", action="store_true")
    parser.add_argument("--init_std", default=0.02, type=float)
    parser.add_argument("--dropout", default=0.0, type=float)
    parser.add_argument("--n_head", default=12, type=int)
    parser.add_argument("--n_layer", default=24, type=int)  # depths in att + ff blocks
    parser.add_argument("--sequence_length", default=512, type=int)
    parser.add_argument("--n_embd", default=768, type=int) # embedding size / hidden size ...
    parser.add_argument("--multiple_of", default=256, type=int) # make SwiGLU hidden layer size multiple of large power of 2
    parser.add_argument("--rmsnorm_eps", default=1e-5, type=float)
    parser.add_argument("--dtype", default="bfloat16", type=str, choices=["float32", "float16", "bfloat16"])
    # parser.add_argument("--model_dtype", default="float32", type=str, choices=["float32", "float16", "bfloat16"])
    parser.add_argument("--bias", default=False, type=bool)
    parser.add_argument("--compile", action="store_true")
    parser.add_argument("--mlp_dim_exp_factor", default=1.0, type=float)

    ### AdamW
    parser.add_argument("--adamw_beta1", default=0.9, type=float)
    parser.add_argument("--adamw_beta2", default=0.95, type=float)
    parser.add_argument("--adamw_eps", default=1e-8, type=float)

    ### CustomEmaAdamW
    parser.add_argument("--custom_ema_adamw_schedule", type=str, default="delayed", choices=["standard", "delayed"])
    parser.add_argument("--custom_ema_adamw_decay", type=int, default=10)
    parser.add_argument("--custom_ema_adamw_alpha", type=float, default=0.001)

    ### FrugalMicroAdam
    parser.add_argument("--frugal_micro_adam_num_grads", type=int, default=10)
    parser.add_argument("--frugal_micro_adam_density", type=float, default=0.01)
    parser.add_argument("--frugal_micro_adam_normalization", type=str, default="standard", choices=["none", "standard"])

    ### ScionedSOAP
    parser.add_argument("--soap_freq", type=int, default=10)
    parser.add_argument("--soap_proj", type=str, default="dct", choices=["evd", "dct", "hdm"])
    parser.add_argument("--soap_rank", default=10) # accepts ints and strings
    parser.add_argument("--soap_beta_left", default=0.95, type=float)
    parser.add_argument("--soap_beta_right", default=0.95, type=float)
    parser.add_argument("--scion_momentum", default=0.95, type=float)
    parser.add_argument("--scion_constrained", type=int, default=0, choices=[0, 1])

    ### Trion
    parser.add_argument("--trion_mu", type=float, default=0.95)
    parser.add_argument("--trion_adam_lr_scaling_factor", type=float, default=100)
    parser.add_argument("--trion_iters", type=int, default=1)
    parser.add_argument("--trion_rank", type=int, default=128)
    parser.add_argument("--trion_update_gap", type=int, default=128)
    # parser.add_argument("--trion_optim", type=str, default='raw', choices=['signsgd', 'sgd', 'adamw', 'raw'])
    parser.add_argument("--trion_lr", type=float, default=1e-3)
    parser.add_argument("--trion_reg_UV", type=float, default=10)
    parser.add_argument("--trion_reg", type=float, default=20)
    parser.add_argument("--trion_method", type=str, default='UV', choices=['UV', 'A'])

    # ### ADOPT
    # parser.add_argument("--adopt_beta1", default=0.9, type=float)
    # parser.add_argument("--adopt_beta2", default=0.9999, type=float)
    # # parser.add_argument("--adopt_use_original", type=int, default=0, choices=[0, 1])

    # ### MARS
    # parser.add_argument("--mars_gamma", default=0.025, type=float)
    # parser.add_argument("--mars_type", default="adamw", type=str, choices=['adamw', 'lion', 'shampoo'])
    #
    # parser.add_argument("--mars_beta1", default=0.95, type=float)
    # parser.add_argument("--mars_beta2", default=0.99, type=float)
    #
    # parser.add_argument("--mars_beta1_1d", default=0.9, type=float)
    # parser.add_argument("--mars_beta2_1d", default=0.95, type=float)
    # parser.add_argument("--mars_weight_decay_1d", default=1e-1, type=float)
    # parser.add_argument("--mars_optimize_1d", type=int, default=0, choices=[0, 1])

    ### Shampoo
    ##### DistributedShampoo

    parser.add_argument("--shmp_beta1", default=0.9, type=float)
    parser.add_argument("--shmp_beta2", default=0.95, type=float)
    parser.add_argument("--shmp_beta_prec", default=0.95, type=float)
    parser.add_argument("--shmp_beta_gg", default=0.05, type=float)

    parser.add_argument("--shmp_clenshaw_version", default=0, type=int)
    parser.add_argument("--shmp_ndb_root4_src", default='sqrt', choices=['sqrt', 'sqrt_inv'], type=str)

    ###### DASH
    parser.add_argument("--shmp_log_stats_interval", default=50, type=int)

    parser.add_argument("--shmp_beta_g", default=0.9, type=float)
    parser.add_argument("--shmp_beta_lr", default=0.9, type=float)
    parser.add_argument("--shmp_beta_graft", default=0.9, type=float)

    parser.add_argument("--shmp_eps_inv_root", default=1e-10, type=float)
    parser.add_argument("--shmp_inv_root_method", default='evd', choices=['evd', 'cn', 'ns', 'cbshv', 'ndb', 'jorge', 'lrpi'], type=str)
    parser.add_argument("--shmp_inv_root_freq", default=10, type=int)

    parser.add_argument("--shmp_grafting_type", default='adam', choices=['adam', 'adagrad'], type=str)
    parser.add_argument("--shmp_grafting_eps", default=1e-8, type=float)

    parser.add_argument("--shmp_mu", default=0.95, type=float)
    parser.add_argument("--shmp_use_nesterov", default=0, choices=[0, 1], type=int)

    parser.add_argument("--shmp_start_prec_step", default=-1, type=int)
    parser.add_argument('--shmp_max_prec_dim', default=1024, type=int)
    parser.add_argument("--shmp_matmul_dtype", default='fp32', choices=['fp16', 'bf16', 'fp32'], type=str)

    parser.add_argument("--shmp_matrix_scaling_type", default='fro', choices=['pi', 'pim', 'fro'], type=str)
    parser.add_argument("--shmp_matrix_scaling_pi_steps", default=10, type=int)
    parser.add_argument("--shmp_matrix_scaling_const", default=2, type=float)
    parser.add_argument("--shmp_newton_steps", default=10, type=int) # NDB & CN
    parser.add_argument("--shmp_algo_one_dim", default='adamw', choices=['adamw', 'shmp'], type=str)

    ########## EVD
    parser.add_argument("--shmp_evd_heuristic", default='shmp', choices=['abs', 'abs-add', 'relu', 'shmp'], type=str)

    ########## CN
    parser.add_argument("--shmp_cn_tolerance", default=1e-6, type=float)

    ########## CBSHV
    parser.add_argument("--shmp_cbshv_degree", default=100, type=int)

    ########## LRPI
    parser.add_argument("--shmp_lrpi_rank", default=100, type=int)
    parser.add_argument("--shmp_lrpi_steps", default=100, type=int)

    # end DASH





    # ### Muon
    parser.add_argument("--muon_type", type=str, default='kj', choices=['ionut', 'cef', 'ef-lr', 'lr', 'hb', 'kj', 'gap-svd', 'gap-ns'])
    parser.add_argument("--muon_proj_type", type=str, default='dion', choices=['dct', 'svd', 'dion'])
    parser.add_argument("--scaling_type", type=str, default='kj', choices=['kj', 'none', 'kimi', 'dion'])
    parser.add_argument("--muon_ns_type", type=str, default='torch', choices=['torch', 'triton'])

    parser.add_argument("--muon_num_blocks", default=0, type=int)
    parser.add_argument("--muon_rank", default=128, type=int)
    parser.add_argument("--muon_gap", default=0, type=int)
    parser.add_argument("--muon_momentum", default=0.95, type=float)
    parser.add_argument("--muon_beta_graft", default=0.95, type=float)
    parser.add_argument("--muon_eps_graft", default=1e-8, type=float)
    # parser.add_argument("--muon_adam_lr_scaling_factor", default=100, type=float)
    parser.add_argument("--muon_adam_lr", type=float, default=1e-2)
    parser.add_argument("--muon_ef_type", type=int, default=0, choices=[0, 1, 2, 3, 4])
    parser.add_argument("--use_makhoul", type=int, default=0, choices=[0, 1])

    # parser.add_argument("--muon_method", type=str, default='NS', choices=['NS', 'SVD', 'QR', 'SIGN'])

    parser.add_argument("--dion_rank", default=128, type=int)
    parser.add_argument("--dion_momentum", default=0.95, type=float)

    parser.add_argument("--ns_dct_dion_rank", default=128, type=int)
    # parser.add_argument("--ns_dct_dion_momentum", default=0.95, type=float)

    # ### SCION
    # parser.add_argument("--scion_momentum", default=0.1, type=float)
    # parser.add_argument("--scion_scale", default=1, type=float)

    # SubTrack
    parser.add_argument("--subtrack_rank", default=128, type=int)
    parser.add_argument("--subtrack_update_gap", default=200, type=int)

    # DCT-AdamW
    parser.add_argument("--dctadamw_rank", default=128, type=int)
    parser.add_argument("--dctadamw_update_gap", default=200, type=int)
    parser.add_argument("--dctadamw_use_ef", type=int, default=0, choices=[0, 1])
    parser.add_argument("--dctadamw_q_ef", type=int, default=0, choices=[0, 4, 8])
    parser.add_argument("--dctadamw_distributed", type=int, default=0, choices=[0, 1])
    parser.add_argument("--dctadamw_rotate_subspace", type=int, default=0, choices=[0, 1])

    return parser.parse_args(args, namespace)
